### ISSUE TITLE
Suggest change `project_name` to lower case

### ISSUE THREAD

**Issue by zufuliu** [tox-dev/pipdeptree#99] opened 2018-05-11 15:28 UTC
Suggest change `project_name` to lower case, since pip package name is case insensitive.
Packages like Pillow, Pygments and PyYAML often has different spellings in other package's dependency list. This will reduce isolated packages / dependencies produced by pipdeptree.

This change only need to add four lines in `build_dist_index`:
```python
    for p in pkgs:
        p.project_name = p.project_name.lower()
        for r in p.requires():
            r.project_name = r.project_name.lower()
    return dict((p.key, DistPackage(p)) for p in pkgs)
```

**Comment by naiquevin** [comment] 2018-05-14 05:00
Can you please open a PR with both this one and #100? Will be easier to test and merge that way.

**Comment by zufuliu** [comment] 2018-05-14 10:54
It's PR #102.

**Comment by sschuberth** [comment] 2019-07-03 07:34
This sound like a duplicate of issue https://github.com/naiquevin/pipdeptree/issues/77.

**Comment by zufuliu** [comment] 2019-07-03 07:51
@sschuberth It's a duplicate, do you have any idea to fix these failed tests in PR #102?

**Comment by naiquevin** [comment] 2019-07-04 17:01
Tests could have failed for completely different reason. The tests have become complicated and messy and I am trying to sort it out. Will test this PR and merge it. Thanks.

**Comment by gaborbernat** [comment] 2022-09-06 07:34
I think we should leave the package name normalization up to pip.

**Closed by gaborbernat** 2022-09-06 07:34 UTC
Labels: bug, duplicate
