### ISSUE TITLE
pipdeptree -r crashes

### ISSUE THREAD

**Issue by yoch** [tox-dev/pipdeptree#142] opened 2020-12-22 13:11 UTC
With the lastest pip version : 

```
Traceback (most recent call last):
  File "/home/ubuntu/env/lib/python3.8/site-packages/pip/_vendor/packaging/requirements.py", line 104, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/home/ubuntu/env/lib/python3.8/site-packages/pip/_vendor/pyparsing.py", line 1955, in parseString
    raise exc
  File "/home/ubuntu/env/lib/python3.8/site-packages/pip/_vendor/pyparsing.py", line 3250, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pip._vendor.pyparsing.ParseException: Expected W:(abcd...), found '-'  (at char 0), (line:1, col:1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/env/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3101, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/home/ubuntu/env/lib/python3.8/site-packages/pip/_vendor/packaging/requirements.py", line 106, in __init__
    raise InvalidRequirement(
pip._vendor.packaging.requirements.InvalidRequirement: Parse error at "'-lib==19'": Expected W:(abcd...)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/env/bin/pipdeptree", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/env/lib/python3.8/site-packages/pipdeptree.py", line 628, in main
    tree = render_tree(tree if not args.reverse else reverse_tree(tree),
  File "/home/ubuntu/env/lib/python3.8/site-packages/pipdeptree.py", line 111, in reverse_tree
    rtree[k.as_requirement()] = []
  File "/home/ubuntu/env/lib/python3.8/site-packages/pipdeptree.py", line 211, in as_requirement
    return ReqPackage(self._obj.as_requirement(), dist=self)
  File "/home/ubuntu/env/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2845, in as_requirement
    return Requirement.parse(spec)
  File "/home/ubuntu/env/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3148, in parse
    req, = parse_requirements(s)
  File "/home/ubuntu/env/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3094, in parse_requirements
    yield Requirement(line)
  File "/home/ubuntu/env/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3103, in __init__
    raise RequirementParseError(str(e))
pip._vendor.pkg_resources.RequirementParseError: Parse error at "'-lib==19'": Expected W:(abcd...)
```

**Comment by naiquevin** [comment] 2020-12-23 13:14
Which version of pipdeptree are you running? Can you please try the
latest beta version or the latest master?

You can install the beta version from pip as follows,

sudo pip install --pre pipdeptree


On Tue, Dec 22, 2020 at 6:41 PM yoch <notifications@github.com> wrote:
>
> With the lastest pip version :
>
> Traceback (most recent call last):
>   File "/home/ubuntu/env/lib/python3.8/site-packages/pip/_vendor/packaging/requirements.py", line 104, in __init__
>     req = REQUIREMENT.parseString(requirement_string)
>   File "/home/ubuntu/env/lib/python3.8/site-packages/pip/_vendor/pyparsing.py", line 1955, in parseString
>     raise exc
>   File "/home/ubuntu/env/lib/python3.8/site-packages/pip/_vendor/pyparsing.py", line 3250, in parseImpl
>     raise ParseException(instring, loc, self.errmsg, self)
> pip._vendor.pyparsing.ParseException: Expected W:(abcd...), found '-'  (at char 0), (line:1, col:1)
>
> During handling of the above exception, another exception occurred:
>
> Traceback (most recent call last):
>   File "/home/ubuntu/env/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3101, in __init__
>     super(Requirement, self).__init__(requirement_string)
>   File "/home/ubuntu/env/lib/python3.8/site-packages/pip/_vendor/packaging/requirements.py", line 106, in __init__
>     raise InvalidRequirement(
> pip._vendor.packaging.requirements.InvalidRequirement: Parse error at "'-lib==19'": Expected W:(abcd...)
>
> During handling of the above exception, another exception occurred:
>
> Traceback (most recent call last):
>   File "/home/ubuntu/env/bin/pipdeptree", line 8, in <module>
>     sys.exit(main())
>   File "/home/ubuntu/env/lib/python3.8/site-packages/pipdeptree.py", line 628, in main
>     tree = render_tree(tree if not args.reverse else reverse_tree(tree),
>   File "/home/ubuntu/env/lib/python3.8/site-packages/pipdeptree.py", line 111, in reverse_tree
>     rtree[k.as_requirement()] = []
>   File "/home/ubuntu/env/lib/python3.8/site-packages/pipdeptree.py", line 211, in as_requirement
>     return ReqPackage(self._obj.as_requirement(), dist=self)
>   File "/home/ubuntu/env/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2845, in as_requirement
>     return Requirement.parse(spec)
>   File "/home/ubuntu/env/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3148, in parse
>     req, = parse_requirements(s)
>   File "/home/ubuntu/env/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3094, in parse_requirements
>     yield Requirement(line)
>   File "/home/ubuntu/env/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3103, in __init__
>     raise RequirementParseError(str(e))
> pip._vendor.pkg_resources.RequirementParseError: Parse error at "'-lib==19'": Expected W:(abcd...)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
~ Vineet

**Comment by yoch** [comment] 2020-12-23 14:25
I used 1.0.0, but he same error occurs with the latest version (2.0.0b1)

**Comment by naiquevin** [comment] 2020-12-23 18:08
I just checked it with latest version of pip `20.3.3` and python 3.6 and it worked fine. It could be some package installed in your env. Can you please paste/attach the output `pip freeze`?

**Comment by yoch** [comment] 2020-12-23 18:32
I use python 3.8.

Here is the output of pip freeze, there is a warning and it looks like it's causing problems for pipdeptree.

NB: The warning itself was caused by a broken residue of dlib package, I deleted it and fixed the error.

```
(env) ubuntu@desktop:~/$ pip freeze
WARNING: Could not generate requirement for distribution -lib 19.20.0 (/home/ubuntu/env/lib/python3.8/site-packages): Parse error at "'-lib==19'": Expected W:(abcd...)
bottle==0.12.19
bottle-sqlalchemy==0.4.3
cachetools==4.2.0
certifi==2020.12.5
cffi==1.14.4
chardet==3.0.4
cryptography==3.3.1
cycler==0.10.0
decorator==4.4.2
dlib==19.21.1
gevent==20.12.0
google-api-core==1.24.1
google-api-python-client==1.12.8
google-auth==1.24.0
google-auth-httplib2==0.0.4
googleapis-common-protos==1.52.0
greenlet==0.4.17
httplib2==0.18.1
idna==2.10
imagecodecs==2020.12.22
imageio==2.9.0
Jinja2==2.11.2
kiwisolver==1.3.1
mailjet-rest==1.3.4
MarkupSafe==1.1.1
matplotlib==3.3.3
networkx==2.5
numpy==1.19.4
oauth2client==4.1.3
opencv-contrib-python==4.4.0.46
pandas==1.1.5
Pillow==8.0.1
pipdeptree==2.0.0b1
pkg-resources==0.0.0
protobuf==3.14.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.20
PyMySQL==0.10.1
pyparsing==2.4.7
python-dateutil==2.8.1
pytz==2020.4
PyWavelets==1.1.1
requests==2.25.1
rsa==4.6
scikit-image==0.17.2
scipy==1.5.4
six==1.15.0
SQLAlchemy==1.3.22
tifffile==2020.12.8
uritemplate==3.0.1
urllib3==1.26.2
XlsxWriter==1.3.7
xmltodict==0.12.0
zope.event==4.5.0
zope.interface==5.2.0
```

**Comment by naiquevin** [comment] 2020-12-24 15:43
Is the problem solved for you? Can you give more details about the residual dlib package? That will help me reproduce the problem. 

I tried to create a virtualenv with the above packages but couldn't install the following ones: 

```
imagecodecs==2020.12.22
pkg-resources==0.0.0
tifffile==2020.12.8
```

In an env with the above 3 packages skipped, I couldn't reproduce the crash.

**Comment by yoch** [comment] 2020-12-24 15:49
Yes, the problem is solved for me.

I don't know why, but in the site-packages there was a directory named "~lib-19.20.0" or something similar, which was clearly a residue from previous installation of dlib. Removing this directory solved my issue.

Thank you for your help !

**Comment by potoo0** [comment] 2021-06-07 06:07
I encountered the same problem, `pip list` have warnings like:
```
WARNING: Could not generate requirement for distribution -upyterlab-code-formatter 1.4.5 (/u01/miniconda3/lib/python3.7/site-packages): Parse error at "'-upyterl'": Expected W:(abcd...)
WARNING: Could not generate requirement for distribution -bdime 3.0.0b1 (/u01/miniconda3/lib/python3.7/site-packages): Parse error at "'-bdime=='": Expected W:(abcd...)
```
truth is that these packages are stored in the site-package directory like
```
# ls /u01/miniconda3/lib/python3.7/site-packages | grep '~'
~bdime
~bdime-3.0.0b1.dist-info
~upyterlab_code_formatter
~upyterlab_code_formatter-1.4.5.dist-info
```
but unfortunately I don’t have permission to operate site-package T_T.

maybe `pipdeptree -r` should skip those broken package like startswith '~'.

**Comment by gaborbernat** [comment] 2022-09-05 03:31
I don't think this should happen, so will close it now, if you run into it again please open a reproducible example again.

**Closed by gaborbernat** 2022-09-05 03:31 UTC
