### ISSUE TITLE
Ability to identify (highlight) binary packages

### ISSUE THREAD

**Issue by ssbarnea** [tox-dev/pipdeptree#137] opened 2020-10-29 08:29 UTC
It would prove very useful to be able to filter or highlight binary packages (non pure-python ones), as these are the most problematic ones to install, especially on across different platforms.

**Comment by gaborbernat** [comment] 2022-09-06 07:41
Duplicate of https://github.com/tox-dev/pipdeptree/issues/79

**Closed by gaborbernat** 2022-09-06 07:41 UTC
