### ISSUE TITLE
version detection problem when conflicting dependencies 

### ISSUE THREAD

**Issue by EricDeveaud** [tox-dev/pipdeptree#112] opened 2019-01-10 13:23 UTC
hello, 
just to let you know that when ```Possibly conflicting dependencies found```
the version detection breaks
see:

````
tars-900:scratch/gensoft_tests > pipdeptree --user    
Warning!!! Possibly conflicting dependencies found:
* h5py==2.8.0
 - numpy [required: >=1.7, installed: ?]
* biom-format==2.1.5
 - numpy [required: >=1.3.0, installed: ?]
 - scipy [required: >=0.13.0, installed: ?]
------------------------------------------------------------------------
biom-format==2.1.5
  - click [required: Any, installed: 7.0]
  - future [required: >=0.14.3, installed: 0.16.0]
  - numpy [required: >=1.3.0, installed: ?]
  - pyqi [required: Any, installed: 0.3.2]
  - scipy [required: >=0.13.0, installed: ?]
h5py==2.8.0
  - numpy [required: >=1.7, installed: ?]
  - six [required: Any, installed: 1.12.0]
```

in this scenario nor installed numpy neither scipy version are detected.

NB: using version 0.13.1

regards

Eric

**Comment by naiquevin** [comment] 2019-01-23 14:36
Thanks for reporting this and sorry about the delay. I will have a look at it soon.

**Comment by xiacunshun** [comment] 2024-04-04 15:32
@EricDeveaud Please test with the newest code to see if this problem exists. We have refactored the code and I can not reproduce it.

**Comment by kemzeb** [comment] 2024-04-18 16:57
I haven't been able to reproduce this when using pipdeptree==0.13.1, biom-format==2.1.5, and pip==18.1 (using this pip version since pidpeptree would crash with modern pip and it was released close to when the user reported this issue):
```console
$ pipdeptree --version
0.13.1
$ pipdeptree --user
biom-format==2.1.5
  - click [required: Any, installed: 8.1.7]
  - future [required: >=0.14.3, installed: 1.0.0]
  - numpy [required: >=1.3.0, installed: 1.24.4]
  - scipy [required: >=0.13.0, installed: 1.10.1]
    - numpy [required: >=1.19.5,<1.27.0, installed: 1.24.4]
. . .
```

Comparing this with the reporter's output, to me it looks like either numpy and scipy aren't installed or an older pip was being used that had issues when looking for installed packages. Going to close this since I can't reproduce and no other users have had similar issues 👍

**Closed by kemzeb** 2024-04-18 16:57 UTC
Labels: bug, help-wanted
